/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Footer() {
  return (
    <footer className="flex flex-wrap gap-5 justify-between mt-32 mb-12 ml-14 mr-32 max-w-full text-xl text-black  max-md:mt-10 max-md:max-w-full">
      <div className="flex flex-col font-light leading-7 max-md:max-w-full">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/61b6433c9998c44721988d99cdf66baa539b867c5f2652d6c6171391e128d8b0?placeholderIfAbsent=true&apiKey=42bb954c825745999302100cb42c8fd0"
          alt="Company logo"
          className="object-contain max-w-full aspect-[2.84] w-[400px]"
        />
        <div className="mt-6 ml-4 max-md:max-w-full">
          We're India's first ever online marketplace 
          <p> offering users to buy and
          sell their digital assets.</p>
        </div>
      </div>
      <nav className="flex gap-10 self-start leading-6 ">
        <ul className="">
        <li className="mb-4">Mango</li>
        <li className="mb-4">Assets</li>
        <li className="mb-4">Careers</li>
        <li className="mb-4">Contact Us</li>
        </ul>
        <ul>
          <li className="mb-4" >For Sellers</li>
          <li className="mb-4">Get Access</li>
          <li className="mb-4">Mango VC</li>
        </ul>
      </nav>
    </footer>
  );
}

export default Footer;
