/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Header = () => {
  return (
    <header className="flex flex-wrap gap-5 justify-between w-full text-2xl font-medium text-black max-w-[1325px] max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/bf4b44c8ccffcd7b79c32192f2bf19fddbab27b93d49a90026b04e9fa8145eee?placeholderIfAbsent=true&apiKey=c59f5e5e431d46fb9fcb854f2676cd03"
        alt="Company logo"
        className="object-contain shrink-0 max-w-full aspect-[2.86] w-[200px]"
      />
      <nav className="flex flex-wrap gap-8 items-center my-auto max-md:max-w-full">
        <a
          to="#categories"
          className="overflow-hidden z-10 self-stretch pt-0 my-auto max-md:pr-0"
        >
          Categories
        </a>
        <a
          to="#pricing"
          className="overflow-hidden z-10 self-stretch pt-0 my-auto"
        >
          Pricing
        </a>
        <a
          to="#about"
          className="overflow-hidden z-10 self-stretch pt-0 my-auto"
        >
          About Us
        </a>
        <a
          to="#access"
          className="self-stretch px-9 pt-3 pb-8 font-extrabold text-white bg-black rounded-xl max-md:px-5"
        >
          Get Access
        </a>
      </nav>
    </header>
  );
};

export default Header;
