/**
 * This code was generated by Builder.io.
 */
import React from "react";

const HeroSection = () => {
  return (
    <section className="flex relative z-10 flex-col justify-center items-center px-20 py-32 mt-5 mr-0 text-center text-black min-h-[669px] max-md:px-5 max-md:py-24 max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/caa792a2b34c897848607ceff3cdbe0b128030421852d05a99a95b1d54a5802c?placeholderIfAbsent=true&apiKey=c59f5e5e431d46fb9fcb854f2676cd03"
        alt=""
        className="object-cover absolute inset-0 size-full"
      />
      <div className="flex relative flex-col items-center max-w-full w-[628px]">
        <h1 className="self-stretch text-5xl font-bold leading-[60px] max-md:max-w-full max-md:text-4xl max-md:leading-[56px]">
          <span className="text-indigo-400">Buy</span> and{" "}
          <span className="text-indigo-400">Sell</span> Digital Assets Online
          For <span className="text-indigo-400">India's</span> top{" "}
          <span className="text-indigo-400">go</span>-
          <span className="text-indigo-400">getters</span>
        </h1>
        <p className="mt-6 text-xl w-[437px] max-md:max-w-full">
          Your gateway to India's finest ventures. No{" "}
          <span className="text-black">middlemen</span>. No barriers. Just
          acquire, grow, and excel.
        </p>
        <a
          href="#explore"
          className="px-14 pt-3 pb-4 mt-12 max-w-full text-3xl font-extrabold bg-indigo-400 rounded-xl text-zinc-100 w-[300px] max-md:px-5 max-md:mt-10"
        >
          Explore Now
        </a>
      </div>
    </section>
  );
};

export default HeroSection;
