export const data=[
    {
        "url":"https://flippa.com/11750434",
        "image":"https://static2.flippa.com/blurred_thumbnail-c2392c14-2a51-a8ed-93f8-b15be609acf6.png",
        "title":"SaaS | Business",
        "listing_type":"Verified Listing",
        "country":"FL, United States",
        "description":"A legendary analytics platform that helps businesses understand customer behavior, optimize conversion rates, and drive revenue growth.",
        "business_type":"Business",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"16 years",
        "netProfit":"USD $15,250 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $2,000,000",
        "multiple_label":"Multiple",
        "profit_multiple":"10.9x Profit",
        "revenue_multiple":"2.1x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $2,000,000"
    },
    {
        "url":"https://flippa.com/11707612",
        "image":"https://static2.flippa.com/blurred_thumbnail-3aad95db-7b3d-4d27-48b0-95fafc54a1cb.png",
        "title":"SaaS | Sports and Outdoor",
        "listing_type":"Verified Listing",
        "country":"United Kingdom",
        "description":"Award-winning 10-year-old sports data and analytics platform (Football/Soccer) | 150% Year-on-Year Growth |~80% of UK customers with potential to grow in the US",
        "business_type":"Sports and Outdoor",
        "revenue_model":"Affiliate Sales",
        "years_operating":"10 years",
        "netProfit":"USD $31,358 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $1,250,000",
        "multiple_label":"Multiple",
        "profit_multiple":"2.8x Profit",
        "revenue_multiple":"2.4x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $1,055,543"
    },
    {
        "url":"https://flippa.com/11537257",
        "image":"https://static2.flippa.com/blurred_thumbnail-032ad701-479b-fa62-f4cf-2aa9d4ced852.png",
        "title":"SaaS | Internet",
        "listing_type":"Verified Listing",
        "country":"India",
        "description":"This business represents an exceptional opportunity, boasting a well-established brand, steadily increasing revenue, a proven and successful business model.",
        "business_type":"Internet",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"12 years",
        "netProfit":"USD $10,066 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $465,000",
        "multiple_label":"Multiple",
        "profit_multiple":"3.5x Profit",
        "revenue_multiple":"2.9x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $419,662"
    },
    {
        "url":"https://flippa.com/11725054",
        "image":"https://static2.flippa.com/blurred_thumbnail-ce120ca3-e6bb-80b8-3f4e-f22268834991.png",
        "title":"SaaS | Business",
        "listing_type":"Verified Listing",
        "country":"DE, United States",
        "description":"8 Years, Beginner Friendly SaaS Agency, 42% Profit Margin, Fully Outsourced, $2.1m Revenue, $943k Net Profit, $1.15 Million In Contract, 90% Seller Financing.",
        "business_type":"Business",
        "revenue_model":"Other",
        "years_operating":"8 years",
        "netProfit":"USD $36,681 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $2,331,950",
        "multiple_label":"Multiple",
        "profit_multiple":"5.3x Profit",
        "revenue_multiple":"2.3x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $2,331,950"
    },
    {
        "url":"https://flippa.com/11413188",
        "image":"https://static2.flippa.com/blurred_thumbnail-cc111e72-01b8-3580-5dab-6750663fdbda.png",
        "title":"SaaS | Business",
        "listing_type":"Verified Listing",
        "country":"ID, United States",
        "description":"Workflow / process management app & Chrome extension for managing Standard Operating Procedures (SOPs). ~62% monthly profit margin. ChatGPT (AI) recently added!",
        "business_type":"Business",
        "revenue_model":"Affiliate Sales",
        "years_operating":"6 years",
        "netProfit":"USD $5,550 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $449,000",
        "multiple_label":"Multiple",
        "profit_multiple":"6.7x Profit",
        "revenue_multiple":"3.7x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $449,000"
    },
    {
        "url":"https://flippa.com/11773818",
        "image":"https://static2.flippa.com/blurred_thumbnail-fef8c3e3-487d-184b-3bad-a5a3f531250f.png",
        "title":"SaaS | Business",
        "listing_type":"Verified Listing",
        "country":"CA, United States",
        "description":"15 y/o iPaaS specializing in Salesforce and NetSuite generating $729K revenue with a 1.5% churn rate. Steady business and set to scale with the right investor.",
        "business_type":"Business",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"15 years",
        "netProfit":"USD $40,872 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $2,500,000",
        "multiple_label":"Multiple",
        "profit_multiple":"5.1x Profit",
        "revenue_multiple":"3.5x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $2,500,000"
    },
    {
        "url":"https://flippa.com/11801618",
        "image":"https://static2.flippa.com/blurred_thumbnail-b1d9b5c6-e223-74f2-7906-7c24936f8bfd.png",
        "title":"Website | Business",
        "listing_type":"Verified Listing",
        "country":"United Kingdom",
        "description":"High growth scalable app monetization platform with $1.2M in revenue and almost $400k profit/year! Priced at 6.77x Profit",
        "business_type":"Business",
        "revenue_model":"Affiliate Sales",
        "years_operating":"1 year",
        "netProfit":"GBP €21,683 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $1,248,018",
        "multiple_label":"Multiple",
        "profit_multiple":"3.7x Profit",
        "revenue_multiple":"1.1x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $1,248,018"
    },
    {
        "url":"https://flippa.com/11794171",
        "image":"https://static2.flippa.com/webp_21c6de20-c09a-4f1c-af44-f99c62ea4614.PNG",
        "title":"Reading Teacher",
        "listing_type":"Verified Listing",
        "country":"NY, United States",
        "description":"Fully Automated  Diverse Revenue SaaS learn-to-read English program used by thousands of teachers worldwide.  Email List is Primed for Conversion.",
        "business_type":"Education",
        "revenue_model":"Ads",
        "years_operating":"19 years",
        "netProfit":"USD $765 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $49,653",
        "multiple_label":"Multiple",
        "profit_multiple":"6x Profit",
        "revenue_multiple":"4.5x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $49,653"
    },
    {
        "url":"https://flippa.com/11720057",
        "image":"https://static2.flippa.com/webp_3d7e5e2e-05a9-4ee6-8a45-5ca01f802303.png",
        "title":"TypingTestPro.com",
        "listing_type":"Verified Listing",
        "country":"Finland",
        "description":"Acquire TypingTestPro: Premier SaaS for recruiters to assess typing skills. Scalable, tech-driven, with a solid user base and growth potential.",
        "business_type":"Business",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"22 years",
        "netProfit":"USD $8,489 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $500,000",
        "multiple_label":"Multiple",
        "profit_multiple":"4.9x Profit",
        "revenue_multiple":"4.4x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $500,000"
    },
    {
        "url":"https://flippa.com/11665598",
        "image":"https://static2.flippa.com/blurred_thumbnail-de807962-ede9-0b58-0d86-e3b2710b1143.jpg",
        "title":"SaaS | Business",
        "listing_type":"Verified Listing",
        "country":"Luxembourg",
        "description":"SponsorMyEvent is the marketplace for event sponsorships_x000d_\nwith up to 13,000 sign-ups/year. We make it easy for organizers and brands to find each other.",
        "business_type":"Business",
        "revenue_model":"Other",
        "years_operating":"10 years",
        "netProfit":"EUR €876 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $500,000",
        "multiple_label":"Multiple",
        "profit_multiple":"11.2x Profit",
        "revenue_multiple":"6.6x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $128,687"
    },
    {
        "url":"https://flippa.com/11622680",
        "image":"https://static2.flippa.com/blurred_thumbnail-48e3ce9f-35d2-4934-ff74-d9a168285f1c.png",
        "title":"SaaS | Business",
        "listing_type":"Verified Listing",
        "description":"Highly Trusted 10 Year Old Time Tracking SaaS Platform at $497,748 USD ARR and Growing!",
        "business_type":"Business",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"11 years",
        "netProfit":"EUR €8,985 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $3,100,000",
        "multiple_label":"Multiple",
        "profit_multiple":"26.3x Profit",
        "revenue_multiple":"6x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $3,100,000"
    },
    {
        "url":"https://flippa.com/11742860",
        "image":"https://static2.flippa.com/blurred_thumbnail-67916e86-eb7b-eb4b-5149-16c0aa58dc3d.png",
        "title":"SaaS | Business",
        "listing_type":"Verified Listing",
        "country":"United Kingdom",
        "description":"Cloud-based SaaS platform enabling businesses with no technical knowledge or coding skills to create their own native mobile app and publish in the app stores.",
        "business_type":"Business",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"13 years",
        "netProfit":"GBP €36,228 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $2,405,243",
        "multiple_label":"Multiple",
        "profit_multiple":"4.2x Profit",
        "revenue_multiple":"2.2x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $2,405,243"
    },
    {
        "url":"https://flippa.com/11698163",
        "image":"https://static2.flippa.com/blurred_thumbnail-9e120248-d84a-536e-04e6-9d25aede3928.png",
        "title":"SaaS | Internet",
        "listing_type":"Verified Listing",
        "country":"Thailand",
        "description":"Ad-Driven Adult File Hosting Platform w/ 50,000,000+ visitors/month AND $1,437,000 in Avg. Yearly Profit 2021-2023! *Limited Time Non-Negotiable Cash Discount*",
        "business_type":"Internet",
        "revenue_model":"Affiliate Sales",
        "years_operating":"4 years",
        "netProfit":"USD $96,738 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $4,500,000",
        "multiple_label":"Multiple",
        "profit_multiple":"3.1x Profit",
        "revenue_multiple":"2.2x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $3,600,000"
    },
    {
        "url":"https://flippa.com/11705872",
        "image":"https://static2.flippa.com/blurred_thumbnail-4503fe9a-7140-fa35-8b80-d1b8c9ab8386.png",
        "title":"SaaS | Internet",
        "listing_type":"Verified Listing",
        "country":"DE, United States",
        "description":"Established SaaS business in the Email Marketing industry with solid revenue, profit margin, and domain authority. Impressive track record since 2012.",
        "business_type":"Internet",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"11 years",
        "netProfit":"USD $6,878 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $431,000",
        "multiple_label":"Multiple",
        "profit_multiple":"3x Profit",
        "revenue_multiple":"0.9x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $245,000"
    },
    {
        "url":"https://flippa.com/11746167",
        "image":"https://static2.flippa.com/blurred_thumbnail-155ca0de-fe98-a391-0409-829de4b06636.png",
        "title":"SaaS | Business",
        "listing_type":"Verified Listing",
        "country":"Ireland",
        "description":"Profitable 7 Y/O Excel App for Institutional Traders/Investors - Priced at 3.3x ARR and growing!",
        "business_type":"Business",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"7 years",
        "netProfit":"USD $7,507 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $1,040,000",
        "multiple_label":"Multiple",
        "profit_multiple":"11.5x Profit",
        "revenue_multiple":"3.7x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $1,040,000"
    },
    {
        "url":"https://flippa.com/11776213",
        "image":"https://static2.flippa.com/blurred_thumbnail-2076e401-b7f1-0602-adcd-48b53129cbcc.png",
        "title":"SaaS | Business",
        "listing_type":"Verified Listing",
        "country":"Mexico",
        "description":"12 Year Old DEI SaaS Job Marketplace for Mexican Women",
        "business_type":"Business",
        "revenue_model":"Affiliate Sales",
        "years_operating":"12 years",
        "netProfit":null,
        "pricing_label":"Asking price",
        "price":"USD $1,550,000",
        "multiple_label":null,
        "profit_multiple":null,
        "revenue_multiple":null,
        "final_pricing_label":"Asking price",
        "final_price":"USD $1,550,000"
    },
    {
        "url":"https://flippa.com/11216294",
        "image":"https://static2.flippa.com/blurred_thumbnail-0416ebcd-7a6a-6490-48b6-a1f5dd5f1b93.png",
        "title":"SaaS | Education",
        "listing_type":"Verified Listing",
        "country":"DE, United States",
        "description":"Scholarships platform for students to simplify the application process with $5.95MM TTM Revenue.",
        "business_type":"Education",
        "revenue_model":"Other",
        "years_operating":"9 years",
        "netProfit":"USD $22,819 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $40,000,000",
        "multiple_label":"Multiple",
        "profit_multiple":"146.1x Profit",
        "revenue_multiple":"7.8x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $40,000,000"
    },
    {
        "url":"https://flippa.com/11730414",
        "image":"https://static2.flippa.com/blurred_thumbnail-04d93e1b-d439-8262-2935-6e568df00267.png",
        "title":"SaaS | Health and Beauty",
        "listing_type":"Verified Listing",
        "country":"FL, United States",
        "description":"An established fitness brand with millions of followers selling its streaming membership business and associated social channels with MRR.",
        "business_type":"Health and Beauty",
        "revenue_model":"Affiliate Sales",
        "years_operating":"6 years",
        "netProfit":"USD $4,128 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $249,000",
        "multiple_label":"Multiple",
        "profit_multiple":"4x Profit",
        "revenue_multiple":"2x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $199,000"
    },
    {
        "url":"https://flippa.com/11736662",
        "image":"https://static2.flippa.com/blurred_thumbnail-c8180559-0738-edd8-fc85-764ff31ec3fa.png",
        "title":"SaaS | Business",
        "listing_type":"Verified Listing",
        "country":"FL, United States",
        "description":"Lead generation platform for businesses to generate and build email lists. 100% Organic Traffic.",
        "business_type":"Business",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"2 years",
        "netProfit":"USD $36,980 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $1,300,000",
        "multiple_label":"Multiple",
        "profit_multiple":"2.9x Profit",
        "revenue_multiple":"2.4x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $1,300,000"
    },
    {
        "url":"https://flippa.com/11656490",
        "image":"https://static2.flippa.com/blurred_thumbnail-aa1e9a52-db85-8689-f68a-52aea7b50572.png",
        "title":"SaaS | Business",
        "listing_type":"Verified Listing",
        "country":"Hungary",
        "description":"18-year-old EU Cyber Security Software Distributor/Reseller in Protected Market - Priced at 3.56x Revenue!",
        "business_type":"Business",
        "revenue_model":"Affiliate Sales",
        "years_operating":"20 years",
        "netProfit":"EUR €101,327 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $15,300,000",
        "multiple_label":"Multiple",
        "profit_multiple":"11.5x Profit",
        "revenue_multiple":"3.4x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $15,300,000"
    },
    {
        "url":"https://flippa.com/11816487",
        "image":"https://static2.flippa.com/webp_6b4d0cb8-8e9e-4965-aeee-36ea91be6855.png",
        "title":"SaaS | Exclusive TV Streaming (ProLive.tv)",
        "listing_type":"Verified Listing",
        "country":"Mauritius",
        "description":"ProLive.tv: Exclusive Access to High-Traffic TV Streaming. Simpler, More Profitable, Earn $10k-$20k Monthly",
        "business_type":"Entertainment",
        "revenue_model":"Ads",
        "years_operating":"4 years",
        "netProfit":"USD $5,173 p/mo",
        "pricing_label":null,
        "price":"USD $505",
        "multiple_label":"Multiple",
        "profit_multiple":"4.4x Profit",
        "revenue_multiple":"4.1x Revenue",
        "final_pricing_label":"25 days left",
        "final_price":"USD $505"
    },
    {
        "url":"https://flippa.com/11761490",
        "image":"https://static2.flippa.com/webp_e18f5594-29a0-4ae0-ae38-646e40c6fbeb.png",
        "title":"Blockbasis.com",
        "listing_type":"Verified Listing",
        "country":"Denmark",
        "description":"20K+ subscriber crypto newsletter with a SaaS tool with $60K annual revenue from sponsors and 70+ paid subs with 100 more on free trial!",
        "business_type":"Internet",
        "revenue_model":"Ads",
        "years_operating":"<1 year",
        "netProfit":"USD $2,380 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $20,000",
        "multiple_label":"Multiple",
        "profit_multiple":"1.7x Profit",
        "revenue_multiple":"1.6x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $20,000"
    },
    {
        "url":"https://flippa.com/11814168",
        "image":"https://static2.flippa.com/blurred_thumbnail-7b3b30fc-3a82-3ffa-eca3-0e94f7767360.png",
        "title":"Website | Business",
        "listing_type":"Verified Listing",
        "country":"Spain",
        "description":"This website is a platform and SAAS for collectors and art lovers to buy, sell, and trade rare and limited artworks and editions within a dedicated community.",
        "business_type":"Business",
        "revenue_model":"Affiliate Sales",
        "years_operating":"7 years",
        "netProfit":"EUR €8,603 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $313,328",
        "multiple_label":"Multiple",
        "profit_multiple":"2.5x Profit",
        "revenue_multiple":"0.5x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $281,464"
    },
    {
        "url":"https://flippa.com/11370098",
        "image":"https://static2.flippa.com/blurred_thumbnail-72542868-e21e-b49b-d4bd-aa6ff583ff9b.png",
        "title":"SaaS | Entertainment",
        "listing_type":"Verified Listing",
        "country":"Indonesia",
        "description":"10 y/o Indonesian SaaS platform for content creators to accept tips and sell digital content. 1.6M+ unique visitors monthly generating $56K+ revenue monthly.",
        "business_type":"Entertainment",
        "revenue_model":"Other",
        "years_operating":"10 years",
        "netProfit":"USD $19,033 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $5,808,750",
        "multiple_label":"Multiple",
        "profit_multiple":"25.4x Profit",
        "revenue_multiple":"10x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $5,808,750"
    },
    {
        "url":"https://flippa.com/11732206",
        "image":"https://static2.flippa.com/blurred_thumbnail-4933826f-56b6-de93-64ff-9a7b27eae5a9.png",
        "title":"SaaS | Internet",
        "listing_type":"Verified Listing",
        "country":"UT, United States",
        "description":"An established SAAS collection of apps skipping the blood, sweat & tears it takes to go from concept to working live solution. Avg Customer LTV: $87.50",
        "business_type":"Internet",
        "revenue_model":"Affiliate Sales",
        "years_operating":"8 years",
        "netProfit":"USD $2,250 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $95,000",
        "multiple_label":"Multiple",
        "profit_multiple":"2.1x Profit",
        "revenue_multiple":"1.2x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $55,597"
    },
    {
        "url":"https://flippa.com/11680924",
        "image":"https://static2.flippa.com/blurred_thumbnail-704bf516-c3d6-c2de-a8cb-a7acdae6e5f2.png",
        "title":"SaaS | Business",
        "listing_type":"Verified Listing",
        "country":"NV, United States",
        "description":"16-year-old live and virtual event technology company providing cutting-edge solutions across various industries. Well-positioned for continued growth.",
        "business_type":"Business",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"16 years",
        "netProfit":"USD $49,087 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $3,900,000",
        "multiple_label":"Multiple",
        "profit_multiple":"2.7x Profit",
        "revenue_multiple":"0.9x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $1,600,000"
    },
    {
        "url":"https://flippa.com/11765037",
        "image":"https://static2.flippa.com/blurred_thumbnail-ff86d35b-41ad-1f00-dcf5-7dc03634ee19.png",
        "title":"SaaS | Internet",
        "listing_type":"Verified Listing",
        "country":"Indonesia",
        "description":"A Pinterest marketing tool that helps you drive traffic by generating and scheduling Pinterest content for your website and ecommerce stores at scale.",
        "business_type":"Internet",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"2 years",
        "netProfit":"USD $24,787 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $1,700,000",
        "multiple_label":"Multiple",
        "profit_multiple":"5.7x Profit",
        "revenue_multiple":"4.2x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $1,700,000"
    },
    {
        "url":"https://flippa.com/11636663",
        "image":"https://static2.flippa.com/blurred_thumbnail-6780f507-cd9f-fa68-0cca-86705bd93924.png",
        "title":"SaaS | Internet",
        "listing_type":"Verified Listing",
        "country":"United Arab Emirates",
        "description":"6 yr old SaaS Apps Brand Making $1m+ EBITDA over the last 12 months",
        "business_type":"Internet",
        "revenue_model":"Affiliate Sales",
        "years_operating":"6 years",
        "netProfit":"USD $70,889 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $4,000,000",
        "multiple_label":"Multiple",
        "profit_multiple":"2.4x Profit",
        "revenue_multiple":"2x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $2,000,000"
    },
    {
        "url":"https://flippa.com/11702490",
        "image":"https://static2.flippa.com/webp_f97d1242-d147-4ccf-9ec0-8a90be0ff5de.png",
        "title":"ITBriefcase.net",
        "listing_type":"Verified Listing",
        "country":"NY, United States",
        "description":"Armed with over 14 years in the tech industry, an esteemed online publication widely embraced by a subscriber base of 400,000 tech professionals.",
        "business_type":"Internet",
        "revenue_model":"Affiliate Sales",
        "years_operating":"15 years",
        "netProfit":"USD $8,255 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $450,000",
        "multiple_label":"Multiple",
        "profit_multiple":"3.5x Profit",
        "revenue_multiple":"3.3x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $350,000"
    },
    {
        "url":"https://flippa.com/11735640",
        "image":"https://static2.flippa.com/webp_6051bae9-bb9e-4316-ba5d-e197e28ec61c.png",
        "title":"fantasyonlinesports.com",
        "listing_type":null,
        "country":"United Kingdom",
        "description":"On offer is a Daily Fantasy Sports Business with exclusive ownership of the code with a White Label Integration which can be cloned and sold for $5k each.",
        "business_type":"Hobbies and Games",
        "revenue_model":"Affiliate Sales",
        "years_operating":"4 years",
        "netProfit":"USD $916 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $8,900",
        "multiple_label":"Multiple",
        "profit_multiple":"0.8x Profit",
        "revenue_multiple":"0.8x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $8,900"
    },
    {
        "url":"https://flippa.com/11650159",
        "image":"https://static2.flippa.com/blurred_thumbnail-eedffa88-6f9a-5319-9b71-2af0f87b5b8a.png",
        "title":"SaaS | Internet",
        "listing_type":"Verified Listing",
        "country":"South Africa",
        "description":"Price lowered! 4-year-old B2B Email Outreach Value-Added SaaS Service, Priced at less than 1.8x Revenue and 9.5x profit",
        "business_type":"Internet",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"5 years",
        "netProfit":"USD $8,591 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $3,100,000",
        "multiple_label":"Multiple",
        "profit_multiple":"14.6x Profit",
        "revenue_multiple":"1.9x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $1,500,000"
    },
    {
        "url":"https://flippa.com/11627912",
        "image":"https://static2.flippa.com/webp_72da8f42-a8ae-4955-9a9d-c32c22219517.png",
        "title":"Goso.io",
        "listing_type":"Verified Listing",
        "country":"Gibraltar",
        "description":"#1 Instagram growth company as mentioned in Forbes for it's advanced technology. Super easy to run with a very high profit margin, currently at 75%.",
        "business_type":"Internet",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"7 years",
        "netProfit":"USD $13,368 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $660,000",
        "multiple_label":"Multiple",
        "profit_multiple":"3.4x Profit",
        "revenue_multiple":"2.5x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $540,000"
    },
    {
        "url":"https://flippa.com/11685658",
        "image":"https://static2.flippa.com/blurred_thumbnail-58f6a11c-ee28-ba75-2521-c337dd60375e.png",
        "title":"SaaS | Sports and Outdoor",
        "listing_type":"Verified Listing",
        "country":"France",
        "description":"A live streaming software that enables content creators to livestream their sport as if it was on TV",
        "business_type":"Sports and Outdoor",
        "revenue_model":"Other",
        "years_operating":"6 years",
        "netProfit":"EUR €4,136 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $1,301,705",
        "multiple_label":"Multiple",
        "profit_multiple":"24x Profit",
        "revenue_multiple":"5.8x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $1,301,705"
    },
    {
        "url":"https://flippa.com/11765001",
        "image":"https://static2.flippa.com/webp_5c7c87d7-5a3b-4b14-9267-2936c9d0f704.png",
        "title":"juzcasino.com",
        "listing_type":"Verified Listing",
        "country":"India",
        "description":"A 3-year Casino/Betting affiliate site (DA 42 DR 33) which reviews casino brands, and promotes the brands by listing them on the top 10 list across the site.",
        "business_type":"Hobbies and Games",
        "revenue_model":"Affiliate Sales",
        "years_operating":"2 years",
        "netProfit":"USD $2,302 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $8,000",
        "multiple_label":"Multiple",
        "profit_multiple":"0.3x Profit",
        "revenue_multiple":"0.3x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $7,200"
    },
    {
        "url":"https://flippa.com/11688938",
        "image":"https://static2.flippa.com/blurred_thumbnail-80d013d6-b8a4-f3d9-00d6-1a6424e32046.png",
        "title":"SaaS | Internet",
        "listing_type":"Verified Listing",
        "country":"United Kingdom",
        "description":"A cutting-edge tool designed to reduce website bounce rates, boost engagement, and enhance user experience with advanced analytics and optimization features.",
        "business_type":"Internet",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"8 years",
        "netProfit":"USD $6,279 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $475,000",
        "multiple_label":"Multiple",
        "profit_multiple":"6.3x Profit",
        "revenue_multiple":"3.8x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $475,000"
    },
    {
        "url":"https://flippa.com/11312985",
        "image":"https://static2.flippa.com/blurred_thumbnail-55223bdd-3cd0-bea7-e94e-598f9a140f4e.png",
        "title":"SaaS | Internet",
        "listing_type":"Verified Listing",
        "country":"Spain",
        "description":"13-year-old Social Listening company at the forefront of real-time data collection, an invaluable component of many major markets. Annual profit $250k.",
        "business_type":"Internet",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"13 years",
        "netProfit":"USD $13,667 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $500,000",
        "multiple_label":"Multiple",
        "profit_multiple":"2.3x Profit",
        "revenue_multiple":"0.8x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $375,000"
    },
    {
        "url":"https://flippa.com/11768628",
        "image":"https://static2.flippa.com/blurred_thumbnail-4352e682-7768-4d70-8723-ba9b76e39af1.png",
        "title":"SaaS | Business",
        "listing_type":"Verified Listing",
        "country":"CA, United States",
        "description":"SBA pre-approved SMS Marketing Tool with 10+ years of operating history and matured proprietary technology.",
        "business_type":"Business",
        "revenue_model":"Other",
        "years_operating":"16 years",
        "netProfit":"USD $62,738 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $4,000,000",
        "multiple_label":"Multiple",
        "profit_multiple":"5.3x Profit",
        "revenue_multiple":"3.3x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $4,000,000"
    },
    {
        "url":"https://flippa.com/11769714",
        "image":"https://static2.flippa.com/webp_845cb0c7-864d-4bb5-9ee0-70a71e6a30f8.png",
        "title":"semscoop.com",
        "listing_type":"Verified Listing",
        "country":"Egypt",
        "description":"A 5yr-old SaaS w/ a 93% profit margin, 52K+ users, 240K views, 60% engagement rate. It ranks for 1K+ keywords, with 4K+ backlinks and 1K+ referring domains.",
        "business_type":"Internet",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"5 years",
        "netProfit":"USD $672 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $35,000",
        "multiple_label":"Multiple",
        "profit_multiple":"3.9x Profit",
        "revenue_multiple":"3.6x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $31,500"
    },
    {
        "url":"https://flippa.com/11352833",
        "image":"https://static2.flippa.com/blurred_thumbnail-15b3a4e2-3564-e2e9-55f6-fbc032923042.png",
        "title":"SaaS | Hobbies and Games",
        "listing_type":"Verified Listing",
        "country":"France",
        "description":"4 year sport betting industry business with subscription business model. Avg monthly profit $57.3k (past 12 months), Avg monthly profit $101.3k (past 3 months)",
        "business_type":"Hobbies and Games",
        "revenue_model":"Other",
        "years_operating":"5 years",
        "netProfit":"EUR €65,960 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $5,000,000",
        "multiple_label":"Multiple",
        "profit_multiple":"5.8x Profit",
        "revenue_multiple":"4.3x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $5,000,000"
    },
    {
        "url":"https://flippa.com/11715619",
        "image":"https://static2.flippa.com/blurred_thumbnail-47119bda-2c36-0db9-c5e8-7023fec8f01d.png",
        "title":"SaaS | Business",
        "listing_type":"Verified Listing",
        "country":"Canada",
        "description":"Advanced AI trading system that can automate trades, manage trades, & generate trading signals. High profit margin business with potential for more growth.",
        "business_type":"Business",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"3 years",
        "netProfit":"USD $8,712 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $700,000",
        "multiple_label":"Multiple",
        "profit_multiple":"3.3x Profit",
        "revenue_multiple":"2.2x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $350,000"
    },
    {
        "url":"https://flippa.com/11508263",
        "image":"https://static2.flippa.com/blurred_thumbnail-d193bb1c-8b34-da4f-0c92-c992957a304d.png",
        "title":"SaaS | Business",
        "listing_type":"Verified Listing",
        "country":"United Kingdom",
        "description":"SaaS platform for dropshippers & e-commerce businesses to find winning products with advanced Adspy tech & Facebook ad library research tool .",
        "business_type":"Business",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"2 years",
        "netProfit":"USD $4,054 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $145,000",
        "multiple_label":"Multiple",
        "profit_multiple":"2.3x Profit",
        "revenue_multiple":"2x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $110,000"
    },
    {
        "url":"https://flippa.com/11025755",
        "image":"https://static2.flippa.com/webp_dd1414dd-8fce-4d31-994b-a000d4f8868a.jpg",
        "title":"WiFi Text - SMS Text Messaging App",
        "listing_type":"Verified Listing",
        "country":"Canada",
        "description":"Includes iOS / Android and Web App | 50K Registered Users | 100k Page Views / Month | First page of Google for 100's of terms",
        "business_type":"Internet",
        "revenue_model":"Ads",
        "years_operating":"4 years",
        "netProfit":"USD $613 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $36,500",
        "multiple_label":"Multiple",
        "profit_multiple":"5x Profit",
        "revenue_multiple":"4.5x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $36,500"
    },
    {
        "url":"https://flippa.com/11691805",
        "image":"https://static2.flippa.com/webp_ebaf0abd-7875-4c82-9bd0-f2177de8a2ca.jpg",
        "title":"ULEZ",
        "listing_type":"Verified Listing",
        "country":"United Kingdom",
        "description":"A website providing information on London Ultra Low Emission Zone, helping individuals understand how it affects them and promoting greener transportation.",
        "business_type":"Automotive",
        "revenue_model":"Ads",
        "years_operating":"3 years",
        "netProfit":"GBP €1,641 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $101,672",
        "multiple_label":"Multiple",
        "profit_multiple":"4.3x Profit",
        "revenue_multiple":"4.2x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $101,672"
    },
    {
        "url":"https://flippa.com/11770181",
        "image":"https://static2.flippa.com/webp_9ecec245-4cd5-497b-8c15-c87cb12dd84c.png",
        "title":"pushlapwholesale.com",
        "listing_type":"Verified Listing",
        "country":"DE, United States",
        "description":"Push Lap Wholesale is a SaaS tool that helps amazon sellers find profitable products to sell.",
        "business_type":"Business",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"<1 year",
        "netProfit":"USD $1,413 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $35,000",
        "multiple_label":"Multiple",
        "profit_multiple":"1.5x Profit",
        "revenue_multiple":"1.3x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $16,630"
    },
    {
        "url":"https://flippa.com/11645168",
        "image":"https://static2.flippa.com/webp_3171375e-20f5-4acc-9a48-b562d89e44b3.jpg",
        "title":"Amplitrade",
        "listing_type":"Verified Listing",
        "country":"Canada",
        "description":"$13,272/month net profit. Low maintenance. 8-year-old subscription business with intellectual property included. Exponential growth potential. Crypto accepted.",
        "business_type":"Business",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"8 years",
        "netProfit":"USD $13,272 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $795,000",
        "multiple_label":"Multiple",
        "profit_multiple":"5x Profit",
        "revenue_multiple":"3.9x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $795,000"
    },
    {
        "url":"https://flippa.com/11578327",
        "image":"https://static2.flippa.com/blurred_thumbnail-5b63ee78-8a8a-128f-0218-77a6ae54150c.png",
        "title":"SaaS | Internet",
        "listing_type":"Verified Listing",
        "country":"Croatia",
        "description":"A low-churn 10 year old Enterprise MDM software company with notable client base of 1,100 organizations!",
        "business_type":"Internet",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"11 years",
        "netProfit":"EUR €6,983 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $1,456,005",
        "multiple_label":"Multiple",
        "profit_multiple":"15.9x Profit",
        "revenue_multiple":"3x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $1,456,005"
    },
    {
        "url":"https://flippa.com/11642864",
        "image":"https://static2.flippa.com/webp_3a5f0e5c-955c-406c-8b15-03e5fc695aab.png",
        "title":"instinctivenotes.com",
        "listing_type":"Verified Listing",
        "country":"Australia",
        "description":"Profitable SaaS in Allied Health with 82% margin, established in 2012 with $28K AUD yearly revenue. Substantial opportunities for growth.",
        "business_type":"Health and Beauty",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"12 years",
        "netProfit":"AUD $1,953 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $86,018",
        "multiple_label":"Multiple",
        "profit_multiple":"2.6x Profit",
        "revenue_multiple":"2.1x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $41,404"
    },
    {
        "url":"https://flippa.com/11656492",
        "image":"https://static2.flippa.com/blurred_thumbnail-07f6d730-8ed2-6c33-10e7-c931e5f13177.png",
        "title":"SaaS | Business",
        "listing_type":"Verified Listing",
        "country":"Switzerland",
        "description":"9-year-old Swiss SaaS Authentication Platform, focusing on Enterprise Security - Priced at 3.9x ARR",
        "business_type":"Business",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"9 years",
        "netProfit":"USD $5,981 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $5,950,000",
        "multiple_label":"Multiple",
        "profit_multiple":"82.9x Profit",
        "revenue_multiple":"7x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $5,950,000"
    },
    {
        "url":"https://flippa.com/11650459",
        "image":"https://static2.flippa.com/blurred_thumbnail-66048310-1d40-c1f9-0203-ef4ca222d229.png",
        "title":"SaaS | Internet",
        "listing_type":"Verified Listing",
        "country":"India",
        "description":"A WordPress plugin business with 2 plugins and website which generates 12k+ pageviews growing rapidly. Potential for 10x growth.",
        "business_type":"Internet",
        "revenue_model":"Affiliate Sales",
        "years_operating":"6 years",
        "netProfit":"USD $1,667 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $65,000",
        "multiple_label":"Multiple",
        "profit_multiple":"2.9x Profit",
        "revenue_multiple":"2.9x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $58,500"
    },
    {
        "url":"https://flippa.com/11778511",
        "image":"https://static2.flippa.com/webp_fe1ba1a9-f8b1-4288-8e04-39b5acd4067d.png",
        "title":"Twylu",
        "listing_type":"Verified Listing",
        "country":"United Kingdom",
        "description":"Unique SEO internal linking tool offering quick and automatic recommendations",
        "business_type":"Internet",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"3 years",
        "netProfit":"GBP €735 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $12,749",
        "multiple_label":"Multiple",
        "profit_multiple":"1.1x Profit",
        "revenue_multiple":"0.8x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $12,749"
    },
    {
        "url":"https://flippa.com/11532448",
        "image":"https://static2.flippa.com/blurred_thumbnail-aecca362-b179-6a8b-2376-f0d4e218daea.png",
        "title":"SaaS | Health and Beauty",
        "listing_type":"Verified Listing",
        "country":"Romania",
        "description":"Profitable SaaS + whitelabel Mobile App in a trendy niche _x000d_\nThe easiest way for nutrition professionals to grow and scale their nutrition business.  AI powered.",
        "business_type":"Health and Beauty",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"7 years",
        "netProfit":"USD $1,769 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $99,000",
        "multiple_label":"Multiple",
        "profit_multiple":"4.7x Profit",
        "revenue_multiple":"3.8x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $99,000"
    },
    {
        "url":"https://flippa.com/11687060",
        "image":"https://static2.flippa.com/webp_b2b3ea06-8915-4e96-996b-8c3b6e21d634.png",
        "title":"ChefGPT",
        "listing_type":"Verified Listing",
        "country":"Hong Kong",
        "description":"ChefGPT is an AI powered recipe generator that creates tailor-made recipes & meal plans based on dietary restrictions, ingredients and more",
        "business_type":"Food and Drink",
        "revenue_model":"Affiliate Sales",
        "years_operating":"1 year",
        "netProfit":"USD $1,091 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $96,000",
        "multiple_label":"Multiple",
        "profit_multiple":"7.3x Profit",
        "revenue_multiple":"5.5x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $96,000"
    },
    {
        "url":"https://flippa.com/11549720",
        "image":"https://static2.flippa.com/webp_fead285a-9e20-468d-aa7d-432f6715b2ee.png",
        "title":"Marketing Copy AI",
        "listing_type":"Verified Listing",
        "country":"United Kingdom",
        "description":"A platform leveraging AI to generate high-quality marketing copy, helping businesses enhance content creation and save time.",
        "business_type":"Internet",
        "revenue_model":"Other",
        "years_operating":"2 years",
        "netProfit":"USD $1,073 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $40,000",
        "multiple_label":"Multiple",
        "profit_multiple":"2.3x Profit",
        "revenue_multiple":"1.6x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $30,000"
    },
    {
        "url":"https://flippa.com/11705693",
        "image":"https://static2.flippa.com/blurred_thumbnail-c2595b45-7347-cede-30ee-b4f3d47b5ab0.png",
        "title":"SaaS | Business",
        "listing_type":"Verified Listing",
        "country":"WI, United States",
        "description":"SaaS for call tracking & analytics, $262K TTM revenue, $304K ARR, low costs, 89% profit, high retention, growth potential.",
        "business_type":"Business",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"5 years",
        "netProfit":"USD $17,911 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $1,400,000",
        "multiple_label":"Multiple",
        "profit_multiple":"4.4x Profit",
        "revenue_multiple":"3.6x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $950,000"
    },
    {
        "url":"https://flippa.com/11650149",
        "image":"https://static2.flippa.com/blurred_thumbnail-c63b5ab8-f680-dc82-d1ec-d37075aa30e3.png",
        "title":"SaaS | Business",
        "listing_type":null,
        "country":"Germany",
        "description":"20-year-old B2B SaaS company offering technology management software - priced at 5X ARR",
        "business_type":"Business",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"21 years",
        "netProfit":"USD $10,210 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $14,250,000",
        "multiple_label":"Multiple",
        "profit_multiple":"116.3x Profit",
        "revenue_multiple":"6x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $14,250,000"
    },
    {
        "url":"https://flippa.com/11751691",
        "image":"https://static2.flippa.com/webp_432d029e-1f87-42a7-9700-b17dea38ec5e.jpg",
        "title":"SendWo",
        "listing_type":"Verified Listing",
        "country":"DE, United States",
        "description":"We are selling our saas product and service business completely around WhatsApp API. We are reselling the software panel. So you don't get code stack.",
        "business_type":"Internet",
        "revenue_model":"Other",
        "years_operating":"2 years",
        "netProfit":"USD $1,314 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $48,000",
        "multiple_label":"Multiple",
        "profit_multiple":"3x Profit",
        "revenue_multiple":"2.2x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $48,000"
    },
    {
        "url":"https://flippa.com/11789527",
        "image":"https://static2.flippa.com/blurred_thumbnail-614d18cc-5cdc-8c8d-aa44-a43734821b08.jpg",
        "title":"SaaS | Internet",
        "listing_type":"Verified Listing",
        "country":"Estonia",
        "description":"A comprehensive library of components, workflows, and pages for web developers, designed to simplify building websites on Bubble.io and Webflow platforms.",
        "business_type":"Internet",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"1 year",
        "netProfit":"USD $577 p/mo",
        "pricing_label":"Starting Price",
        "price":"USD $12,351",
        "multiple_label":"Multiple",
        "profit_multiple":"2.4x Profit",
        "revenue_multiple":"2.4x Revenue",
        "final_pricing_label":"Starting Price",
        "final_price":"USD $12,351"
    },
    {
        "url":"https://flippa.com/11820899",
        "image":"https://static2.flippa.com/blurred_thumbnail-d1d99597-55ac-cba7-2b8f-f34e51293be4.PNG",
        "title":"Website | Business",
        "listing_type":"Verified Listing",
        "country":"Pakistan",
        "description":"A 6 year old website for YouTube marketing with $500+ in monthly profile. Highly profitable and fully automated",
        "business_type":"Business",
        "revenue_model":"Ads",
        "years_operating":"6 years",
        "netProfit":"USD $398 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $10,000",
        "multiple_label":"Multiple",
        "profit_multiple":"2.1x Profit",
        "revenue_multiple":"1.7x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $10,000"
    },
    {
        "url":"https://flippa.com/11731364",
        "image":"https://static2.flippa.com/blurred_thumbnail-2107a26b-bf16-78b1-379b-d17b85e22ae9.png",
        "title":"SaaS | Internet",
        "listing_type":"Verified Listing",
        "country":"Egypt",
        "description":"2.5 years AI writing saas serves over 400k users and has enormous growth potential. we offer custom AI writing solutions that cater to marketers and writers.",
        "business_type":"Internet",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"3 years",
        "netProfit":"USD $23,652 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $1,150,000",
        "multiple_label":"Multiple",
        "profit_multiple":"2.8x Profit",
        "revenue_multiple":"2.1x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $782,000"
    },
    {
        "url":"https://flippa.com/11639658",
        "image":"https://static2.flippa.com/webp_00e44fed-bf70-46d5-86dd-8ab2931ed88f.png",
        "title":"partyland.io",
        "listing_type":"Verified Listing",
        "country":"Portugal",
        "description":"With volume sales of more then 626 ETH (about 1.3 Million Usd), and 1,061 land owners, this 3 years old website is for sale. To View: https://partyland.io/",
        "business_type":"Internet",
        "revenue_model":"Affiliate Sales",
        "years_operating":"4 years",
        "netProfit":"USD $104,582 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $100,000",
        "multiple_label":"Multiple",
        "profit_multiple":"0.1x Profit",
        "revenue_multiple":"0.1x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $100,000"
    },
    {
        "url":"https://flippa.com/11797441",
        "image":"https://static2.flippa.com/blurred_thumbnail-66b69270-1811-cc5f-29ab-14e20eb5db36.png",
        "title":"SaaS | Business",
        "listing_type":"Verified Listing",
        "country":"GA, United States",
        "description":"Fintology : An AI-powered B2B SaaS for businesses needing to boost sales through our Consumer Finance Solution.",
        "business_type":"Business",
        "revenue_model":"Affiliate Sales",
        "years_operating":"2 years",
        "netProfit":"USD $22,682 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $1,200,000",
        "multiple_label":"Multiple",
        "profit_multiple":"4.4x Profit",
        "revenue_multiple":"1.8x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $1,200,000"
    },
    {
        "url":"https://flippa.com/11768756",
        "image":"https://static2.flippa.com/webp_5fb0bfbe-f5b3-44a0-bf10-6a5195197568.jpg",
        "title":"Wasabi Theme",
        "listing_type":"Verified Listing",
        "country":"United Kingdom",
        "description":"An established All-in-One WordPress Theme for blogging and creating niche sites. Highly profitable and easy to run.",
        "business_type":"Business",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"4 years",
        "netProfit":"GBP €780 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $34,535",
        "multiple_label":"Multiple",
        "profit_multiple":"2.3x Profit",
        "revenue_multiple":"2.1x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $28,683"
    },
    {
        "url":"https://flippa.com/11663000",
        "image":"https://static2.flippa.com/blurred_thumbnail-06418079-5936-0379-e04a-b7ecd0bfdf7d.jpeg",
        "title":"SaaS | Education",
        "listing_type":"Verified Listing",
        "country":"United Arab Emirates",
        "description":"High Demand Prom Farming Company With Proven Results & Track Record!",
        "business_type":"Education",
        "revenue_model":"Affiliate Sales",
        "years_operating":"4 years",
        "netProfit":"USD $45,501 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $999,999",
        "multiple_label":"Multiple",
        "profit_multiple":"0.4x Profit",
        "revenue_multiple":"0.3x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $199,000"
    },
    {
        "url":"https://flippa.com/11653948",
        "image":"https://static2.flippa.com/blurred_thumbnail-54b0d88d-1a24-f81c-5f70-901be5b81850.png",
        "title":"SaaS | Internet",
        "listing_type":"Verified Listing",
        "country":"TX, United States",
        "description":"A unique franchise business model that sells pre-made SAAS businesses, selling an instant app builder, with complete training on how to grow the business.",
        "business_type":"Internet",
        "revenue_model":"Affiliate Sales",
        "years_operating":"2 years",
        "netProfit":"USD $8,603 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $879,000",
        "multiple_label":"Multiple",
        "profit_multiple":"8.5x Profit",
        "revenue_multiple":"1.3x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $879,000"
    },
    {
        "url":"https://flippa.com/11717054",
        "image":"https://static2.flippa.com/blurred_thumbnail-9eadeed8-5810-5d86-b088-9d852bb87bdd.png",
        "title":"SaaS | Education",
        "listing_type":"Verified Listing",
        "country":"British Virgin Islands",
        "description":"Singapore-based B2B SaaS platform for the higher education/training sectors. Sticky enterprise clients with <1% churn rate generating an av $45K annual revenue",
        "business_type":"Education",
        "revenue_model":"Other",
        "years_operating":"4 years",
        "netProfit":"USD $12,506 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $800,000",
        "multiple_label":"Multiple",
        "profit_multiple":"3.3x Profit",
        "revenue_multiple":"2.8x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $500,000"
    },
    {
        "url":"https://flippa.com/11674306",
        "image":"https://static2.flippa.com/webp_86a06049-3c05-4212-91ef-d4ead7204919.png",
        "title":"tacboard.com",
        "listing_type":"Verified Listing",
        "country":"IL, United States",
        "description":"A digital platform offering collaborative virtual whiteboards for seamless team communication and improved productivity.",
        "business_type":"Entertainment",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"8 years",
        "netProfit":"USD $1,968 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $75,000",
        "multiple_label":"Multiple",
        "profit_multiple":"3.2x Profit",
        "revenue_multiple":"2.3x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $75,000"
    },
    {
        "url":"https://flippa.com/11711195",
        "image":"https://static2.flippa.com/blurred_thumbnail-44e919d8-03a4-e9e3-e0c9-92a37608b9b6.png",
        "title":"SaaS | Business",
        "listing_type":null,
        "country":"United Kingdom",
        "description":"4 Y/O Enterprise SaaS Platform for EU Pharma Market - Priced at only 4.37x TTM Profit! Pre-Approved for $375,000 from Boopos",
        "business_type":"Business",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"4 years",
        "netProfit":"USD $15,163 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $1,050,000",
        "multiple_label":"Multiple",
        "profit_multiple":"5.8x Profit",
        "revenue_multiple":"4.8x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $1,050,000"
    },
    {
        "url":"https://flippa.com/11680695",
        "image":"https://static2.flippa.com/blurred_thumbnail-3fcabc2c-9615-4e3a-da23-69b29ffbc799.png",
        "title":"SaaS | Business",
        "listing_type":"Verified Listing",
        "country":"Israel",
        "description":"Innovative software company specializing in data integration and automation solutions, empowering businesses to streamline and optimize their operations.",
        "business_type":"Business",
        "revenue_model":"Other",
        "years_operating":"22 years",
        "netProfit":"USD $75,741 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $10,000,000",
        "multiple_label":"Multiple",
        "profit_multiple":"11x Profit",
        "revenue_multiple":"4.6x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $10,000,000"
    },
    {
        "url":"https://flippa.com/11731703",
        "image":"https://static2.flippa.com/blurred_thumbnail-4160dceb-029e-58d9-e767-df75e710362d.png",
        "title":"SaaS | Business",
        "listing_type":"Verified Listing",
        "country":"Australia",
        "description":"AU B2B scheduling and management SaaS with a CAGR of 14.5%, 500 customers, and over 45K app users. Ready to scale with software for the US, the EU and NZ.",
        "business_type":"Business",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"4 years",
        "netProfit":"AUD $9,434 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $4,700,000",
        "multiple_label":"Multiple",
        "profit_multiple":"61.5x Profit",
        "revenue_multiple":"9.4x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $4,700,000"
    },
    {
        "url":"https://flippa.com/11684707",
        "image":"https://static2.flippa.com/webp_baf959f0-d73f-48d1-877c-4bcb21fc74d4.png",
        "title":"Realms Hosting",
        "listing_type":"Verified Listing",
        "country":"United Kingdom",
        "description":"This enterprise offers hosting services with flexible plans to accommodate diverse needs, ensuring smooth website operations for businesses of all sizes.",
        "business_type":"Hobbies and Games",
        "revenue_model":"Other",
        "years_operating":"4 years",
        "netProfit":"USD $1,519 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $137,500",
        "multiple_label":"Multiple",
        "profit_multiple":"7.5x Profit",
        "revenue_multiple":"2.5x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $137,500"
    },
    {
        "url":"https://flippa.com/11728713",
        "image":"https://static2.flippa.com/webp_2079a1f3-f654-4c93-b528-48371601a46f.png",
        "title":"DigitalJAS Inc.",
        "listing_type":"Verified Listing",
        "country":"Canada",
        "description":"A Shopify Plus partner, our 20 year expertise in Ecommerce Implementation & Growth Strategy helps merchants implement and scale their online business.",
        "business_type":"Business",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"5 years",
        "netProfit":"USD $27,363 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $950,000",
        "multiple_label":"Multiple",
        "profit_multiple":"2.9x Profit",
        "revenue_multiple":"1.8x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $950,000"
    },
    {
        "url":"https://flippa.com/11770228",
        "image":"https://static2.flippa.com/blurred_thumbnail-0f51e608-c7bd-10e6-2519-0bf4606c44e7.jpeg",
        "title":"SaaS | Business",
        "listing_type":"Verified Listing",
        "country":"France",
        "description":"SaaS | Software | Productivity tool offering customizable text expansion to improve efficiency | Earning through subscriptions",
        "business_type":"Business",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"6 years",
        "netProfit":"USD $5,054 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $190,000",
        "multiple_label":"Multiple",
        "profit_multiple":"3.1x Profit",
        "revenue_multiple":"3x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $190,000"
    },
    {
        "url":"https://flippa.com/11730657",
        "image":"https://static2.flippa.com/webp_99e15266-e692-4292-8f8e-a1985f89b36e.png",
        "title":"CannaScale",
        "listing_type":"Verified Listing",
        "country":"South Africa",
        "description":"7-year old email marketing agency within the Cannabis, CBD and Hemp industry, $30k-$40k per month, full experienced team already in place.",
        "business_type":"Business",
        "revenue_model":"Ads",
        "years_operating":"4 years",
        "netProfit":"USD $10,133 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $400,850",
        "multiple_label":"Multiple",
        "profit_multiple":"3x Profit",
        "revenue_multiple":"1.3x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $360,765"
    },
    {
        "url":"https://flippa.com/11771749",
        "image":"https://static2.flippa.com/webp_b06aee07-bd7f-4001-af13-b2db7e6a0183.png",
        "title":"Website creation platform",
        "listing_type":"Verified Listing",
        "country":"Latvia",
        "description":"Platforms for website creation and e-commerce + B2B marketplace in one technical solution. Platforms work in 6 different regions.",
        "business_type":"Internet",
        "revenue_model":"Ads",
        "years_operating":"14 years",
        "netProfit":"EUR €1,199 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $106,541",
        "multiple_label":"Multiple",
        "profit_multiple":"6.6x Profit",
        "revenue_multiple":"3.3x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $104,051"
    },
    {
        "url":"https://flippa.com/11782415",
        "image":"https://static2.flippa.com/webp_f76b3a2b-53b1-4d0f-9c20-ed6002f0c2e3.png",
        "title":"OHMYLEAD",
        "listing_type":"Verified Listing",
        "country":"Morocco",
        "description":"A lead management software with its mobile appa great opportunity to scale quickly and easily raise funds.",
        "business_type":"Business",
        "revenue_model":"Other",
        "years_operating":"6 years",
        "netProfit":"USD $13,833 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $626,340",
        "multiple_label":"Multiple",
        "profit_multiple":"3.8x Profit",
        "revenue_multiple":"3.5x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $626,340"
    },
    {
        "url":"https://flippa.com/11773743",
        "image":"https://static2.flippa.com/webp_e1d6a74e-388e-4503-9978-5dd79533ea54.png",
        "title":"Xpurity",
        "listing_type":"Verified Listing",
        "country":"CO, United States",
        "description":"A complimentary set of branded, turn-key, adult-themed sites (adult social media, microsite, Linktree alternative, Adserver platform).",
        "business_type":"Internet",
        "revenue_model":"Affiliate Sales",
        "years_operating":"5 years",
        "netProfit":"USD $90 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $4,995",
        "multiple_label":"Multiple",
        "profit_multiple":"4.6x Profit",
        "revenue_multiple":"4.6x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $4,995"
    },
    {
        "url":"https://flippa.com/11411849",
        "image":"https://static2.flippa.com/blurred_thumbnail-4e8fe06e-3688-e8b2-5135-54be77c98848.png",
        "title":"SaaS | Business",
        "listing_type":"Verified Listing",
        "country":"Colombia",
        "description":"A 5-year-old omnichannel (WhatsApp, Telegram, FB Messenger, SMS, and Websites) communication automation SaaS tool.",
        "business_type":"Business",
        "revenue_model":"Other",
        "years_operating":"6 years",
        "netProfit":"USD $12,699 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $500,000",
        "multiple_label":"Multiple",
        "profit_multiple":"3.3x Profit",
        "revenue_multiple":"1.3x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $500,000"
    },
    {
        "url":"https://flippa.com/11769184",
        "image":"https://static2.flippa.com/blurred_thumbnail-5ee6c381-b456-a5ce-750a-ba81e8f64531.png",
        "title":"SaaS | Internet",
        "listing_type":null,
        "country":"France",
        "description":"Stop Purchase Abandonment with Real-Time Customer Advocacy.",
        "business_type":"Internet",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"12 years",
        "netProfit":"EUR €1,917 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $111,282",
        "multiple_label":"Multiple",
        "profit_multiple":"4.4x Profit",
        "revenue_multiple":"1.1x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $111,282"
    },
    {
        "url":"https://flippa.com/11769798",
        "image":"https://static2.flippa.com/blurred_thumbnail-6adae7cd-ce84-a727-d6cf-bfe99e073631.png",
        "title":"SaaS | Business",
        "listing_type":"Verified Listing",
        "country":"AZ, United States",
        "description":"Acquire Business Glu, the leading SaaS platform for mobile-first performance teams with recurring revenue and minimal operational overhead",
        "business_type":"Business",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"5 years",
        "netProfit":"USD $3,308 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $75,000",
        "multiple_label":"Multiple",
        "profit_multiple":"1.9x Profit",
        "revenue_multiple":"1.4x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $75,000"
    },
    {
        "url":"https://flippa.com/11738063",
        "image":"https://static2.flippa.com/webp_8d7f2775-9fe5-41de-99d1-f92dafda99eb.png",
        "title":"packagedisabler.com",
        "listing_type":"Verified Listing",
        "country":"United Kingdom",
        "description":"Business offers SaaS solution in the Business industry with strong revenue, high profit margin, and established presence since 2014.",
        "business_type":"Business",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"10 years",
        "netProfit":"USD $5,267 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $195,000",
        "multiple_label":"Multiple",
        "profit_multiple":"3.1x Profit",
        "revenue_multiple":"3x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $195,000"
    },
    {
        "url":"https://flippa.com/11720720",
        "image":"https://static2.flippa.com/webp_febbcc73-3071-462c-bb32-fb6a1a013d35.png",
        "title":"Native Ad Buzz",
        "listing_type":"Verified Listing",
        "country":"Canada",
        "description":"NativeAdBuzz is a powerful SAAS spy tool for native advertising, offering insights into competitors' successful ads across 10 networks and 12 countries.",
        "business_type":"Business",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"9 years",
        "netProfit":null,
        "pricing_label":"Asking price",
        "price":"USD $10,000",
        "multiple_label":null,
        "profit_multiple":null,
        "revenue_multiple":null,
        "final_pricing_label":"Asking price",
        "final_price":"USD $7,500"
    },
    {
        "url":"https://flippa.com/11782262",
        "image":"https://static2.flippa.com/webp_e2b6edce-bd0b-473f-aede-7f65a2af2a14.png",
        "title":"FreeVPN.one",
        "listing_type":"Verified Listing",
        "country":"United Kingdom",
        "description":"Innovative VPN solution with high profit margin and strong industry presence in the Internet sector.",
        "business_type":"Internet",
        "revenue_model":"Ads",
        "years_operating":"4 years",
        "netProfit":"USD $1,188 p/mo",
        "pricing_label":"Starting Price",
        "price":"USD $45,900",
        "multiple_label":"Multiple",
        "profit_multiple":"3.8x Profit",
        "revenue_multiple":"2.8x Revenue",
        "final_pricing_label":"Starting Price",
        "final_price":"USD $45,900"
    },
    {
        "url":"https://flippa.com/11693211",
        "image":"https://static2.flippa.com/blurred_thumbnail-b346f007-a9e8-292d-e651-f2cb4c5543f0.png",
        "title":"SaaS | Internet",
        "listing_type":"Verified Listing",
        "country":"France",
        "description":"Since August 2020, Platform for selling backlinks on monthly subscriptions. FR market. Saas 100% automated.",
        "business_type":"Internet",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"4 years",
        "netProfit":"EUR €9,064 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $326,640",
        "multiple_label":"Multiple",
        "profit_multiple":"1.8x Profit",
        "revenue_multiple":"0.9x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $214,392"
    },
    {
        "url":"https://flippa.com/10925674",
        "image":"https://static2.flippa.com/webp_977abef4-b0c9-4c4f-8bd0-69c044a63c9a.png",
        "title":"soundupnow.com",
        "listing_type":null,
        "country":null,
        "description":"SaaS / Business",
        "business_type":"Business",
        "revenue_model":"Subscription",
        "years_operating":"5 years",
        "netProfit":"USD $458 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $10,000",
        "multiple_label":"Multiple",
        "profit_multiple":"1.8x Profit",
        "revenue_multiple":"0.6x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $10,000"
    },
    {
        "url":"https://flippa.com/11813198",
        "image":"https://static2.flippa.com/blurred_thumbnail-3331ed0d-d84f-5299-4de4-24a04e201d4a.png",
        "title":"SaaS | Sports and Outdoor",
        "listing_type":"Verified Listing",
        "country":"Australia",
        "description":"AU-based Sports SaaS that is digitizing playing sport. Strong YOY growth and 40% in the last 6 months! Low revenue churn rate of 1.3% and an app for 170K+ users",
        "business_type":"Sports and Outdoor",
        "revenue_model":"Other",
        "years_operating":"5 years",
        "netProfit":"AUD $25,299 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $5,538,360",
        "multiple_label":"Multiple",
        "profit_multiple":"27x Profit",
        "revenue_multiple":"7.2x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $5,538,360"
    },
    {
        "url":"https://flippa.com/11778288",
        "image":"https://static2.flippa.com/webp_6776070b-3175-41ee-afed-db91d2c497e7.png",
        "title":"Website-Exchange.com/",
        "listing_type":null,
        "country":"United Kingdom",
        "description":"Website-Exchange.com provides Web design services who prefer websites for business visibility. This successful business resulted in earning $7,377/m.",
        "business_type":"Internet",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"<1 year",
        "netProfit":"USD $7,377 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $35,000",
        "multiple_label":"Multiple",
        "profit_multiple":"0.5x Profit",
        "revenue_multiple":"0.2x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $35,000"
    },
    {
        "url":"https://flippa.com/11819936",
        "image":"https://static2.flippa.com/webp_e3ba3b10-6fe3-4e56-b892-14469445c31e.png",
        "title":"Copymate",
        "listing_type":"Verified Listing",
        "country":"Poland",
        "description":"Innovative AIPowered SEO Content Generator._x000d_\n Trusted and tested by thousands of proffessionals around the globe._x000d_\n_x000d_\n20k+ registered users",
        "business_type":"Internet",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"1 year",
        "netProfit":"USD $7,863 p/mo",
        "pricing_label":"Starting Price",
        "price":"USD $250,000",
        "multiple_label":"Multiple",
        "profit_multiple":"3.4x Profit",
        "revenue_multiple":"3x Revenue",
        "final_pricing_label":"Starting Price",
        "final_price":"USD $250,000"
    },
    {
        "url":"https://flippa.com/11747070",
        "image":"https://static2.flippa.com/webp_ff412222-5221-4e88-a0ad-9a97e1205a04.png",
        "title":"dishgen.com",
        "listing_type":"Verified Listing",
        "country":"CA, United States",
        "description":"Profitable AI recipe generator with 15,000+ users. Web and mobile apps. High-growth Recurring subscription-based revenue. Featured in The Guardian, NPR, & more.",
        "business_type":"Food and Drink",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"1 year",
        "netProfit":"USD $603 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $55,000",
        "multiple_label":"Multiple",
        "profit_multiple":"6.8x Profit",
        "revenue_multiple":"6.1x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $49,500"
    },
    {
        "url":"https://flippa.com/11735948",
        "image":"https://static2.flippa.com/webp_d4165324-04e8-4b9d-96aa-843b490e92f5.png",
        "title":"REMOJO",
        "listing_type":"Verified Listing",
        "country":"United Kingdom",
        "description":"An established SaaS business helping men achieve sexual self-mastery through a suite of 5x native apps (Android, iOS, Windows, Mac, Web), courses and community.",
        "business_type":"Lifestyle",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"4 years",
        "netProfit":"USD $4,158 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $225,000",
        "multiple_label":"Multiple",
        "profit_multiple":"4.5x Profit",
        "revenue_multiple":"1.5x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $225,000"
    },
    {
        "url":"https://flippa.com/11813433",
        "image":"https://static2.flippa.com/blurred_thumbnail-0e44789f-6934-9305-8610-27fa4d4f92e0.png",
        "title":"Website | Health and Beauty",
        "listing_type":"Verified Listing",
        "country":"SC, United States",
        "description":"A profitable SaaS platform that generates custom apps for experts/doctors/coaches to deliver content to, stay connected with and track their clients/patients.",
        "business_type":"Health and Beauty",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"7 years",
        "netProfit":"USD $1,146 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $53,970",
        "multiple_label":"Multiple",
        "profit_multiple":"3.9x Profit",
        "revenue_multiple":"1.5x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $53,970"
    },
    {
        "url":"https://flippa.com/11794008",
        "image":"https://static2.flippa.com/blurred_thumbnail-d588a119-78ab-ae5c-3559-146bee8d5d43.png",
        "title":"SaaS | Internet",
        "listing_type":"Verified Listing",
        "country":"Austria",
        "description":"Unlock productivity with our AI Prompt Tool, a leading SaaS platform: $4.5M ARR, 50% EBITDA margin, and 2.2M users all in just 21 months since launch!",
        "business_type":"Internet",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"1 year",
        "netProfit":"USD $163,284 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $16,000,000",
        "multiple_label":"Multiple",
        "profit_multiple":"8.2x Profit",
        "revenue_multiple":"3.8x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $16,000,000"
    },
    {
        "url":"https://flippa.com/11714915",
        "image":"https://static2.flippa.com/blurred_thumbnail-a0e250ea-1115-a46d-cb33-6bbef1111413.png",
        "title":"SaaS | Business",
        "listing_type":"Verified Listing",
        "country":"Romania",
        "description":"LabelUs is an automated multi vendor Amazon SaaS platform for electronic shelf labels management_x000d_\nMOBIUS price modeling (machine learning) component in roadmap",
        "business_type":"Business",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"2 years",
        "netProfit":"USD $11,256 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $225,000",
        "multiple_label":"Multiple",
        "profit_multiple":"1.7x Profit",
        "revenue_multiple":"1.2x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $225,000"
    },
    {
        "url":"https://flippa.com/11679033",
        "image":"https://static2.flippa.com/blurred_thumbnail-3cfc38da-2ee4-54a2-2d66-c9633d0cd580.png",
        "title":"SaaS | Internet",
        "listing_type":"Verified Listing",
        "country":"TX, United States",
        "description":"A nearly 2 decade old reputable provider of highly affordable, custom software programming led by a small efficient team | 38% profit margin",
        "business_type":"Internet",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"14 years",
        "netProfit":"USD $25,917 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $1,000,000",
        "multiple_label":"Multiple",
        "profit_multiple":"3.2x Profit",
        "revenue_multiple":"1.2x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $1,000,000"
    },
    {
        "url":"https://flippa.com/11765796",
        "image":"https://static2.flippa.com/blurred_thumbnail-513ba7de-de0f-22c0-83d9-b3c53a519718.png",
        "title":"SaaS | Business",
        "listing_type":"Verified Listing",
        "country":"TX, United States",
        "description":"SellerMobile offers a SaaS platform for Amazon and Walmart sellers, providing profit reporting, KPI tracking, inventory management, and repricing tools to boost",
        "business_type":"Business",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"11 years",
        "netProfit":"USD $4,939 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $350,000",
        "multiple_label":"Multiple",
        "profit_multiple":"3.3x Profit",
        "revenue_multiple":"0.9x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $195,000"
    },
    {
        "url":"https://flippa.com/11736386",
        "image":"https://static2.flippa.com/webp_58cd6861-7670-4f37-a2da-f869e8931b6b.png",
        "title":"HeliumTracker.io",
        "listing_type":"Verified Listing",
        "country":"Germany",
        "description":"A 3 year old subscription based project for monitoring helium mining income and managing commissions. Build on ruby on rails. Including mobile app",
        "business_type":"Internet",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"4 years",
        "netProfit":"USD $3,432 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $95,000",
        "multiple_label":"Multiple",
        "profit_multiple":"1.2x Profit",
        "revenue_multiple":"1x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $48,450"
    },
    {
        "url":"https://flippa.com/11675458",
        "image":"https://static2.flippa.com/webp_428592d7-ec43-4bae-b3dc-a0e03a1411e5.png",
        "title":"internwise.co.uk",
        "listing_type":"Verified Listing",
        "country":"United Kingdom",
        "description":"An online job platform connecting businesses with interns, offering a simplified process for recruitment and engagement.",
        "business_type":"Business",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"14 years",
        "netProfit":"GBP €429 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $29,950",
        "multiple_label":"Multiple",
        "profit_multiple":"4.4x Profit",
        "revenue_multiple":"4x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $29,950"
    },
    {
        "url":"https://flippa.com/11764849",
        "image":"https://static2.flippa.com/blurred_thumbnail-15706657-e0a4-eed2-f4da-8d34a524b25d.png",
        "title":"SaaS | Internet",
        "listing_type":"Verified Listing",
        "country":"DE, United States",
        "description":"B2B Lead Finding SaaS with 12million records of ecommerce stores as well as other tools for a quick sale.",
        "business_type":"Internet",
        "revenue_model":"Other",
        "years_operating":"1 year",
        "netProfit":"USD $115 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $12,000",
        "multiple_label":"Multiple",
        "profit_multiple":"3.5x Profit",
        "revenue_multiple":"2.2x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $4,049"
    },
    {
        "url":"https://flippa.com/11779830",
        "image":"https://static2.flippa.com/webp_bbb92b42-9759-498f-921d-c79e541049dd.png",
        "title":"Bi Gelistir | Generate idea, earn money!",
        "listing_type":"Verified Listing",
        "country":"CA, United States",
        "description":"An extraordinary platform born from a unique idea, with high earning potential through subscriptions, advertising spaces, commissions, and additional fees!",
        "business_type":"Internet",
        "revenue_model":"Affiliate Sales",
        "years_operating":"1 year",
        "netProfit":"USD $2,063 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $64,999",
        "multiple_label":"Multiple",
        "profit_multiple":"2.6x Profit",
        "revenue_multiple":"2.6x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $64,999"
    },
    {
        "url":"https://flippa.com/11532456",
        "image":"https://static2.flippa.com/blurred_thumbnail-455db20a-8ace-c13e-5fc4-17a3c2600a01.jpg",
        "title":"SaaS | Business",
        "listing_type":"Verified Listing",
        "country":"United Kingdom",
        "description":"A self serving interactive content  platform producing microsites in a shape of an interactive digital publication, media hubs with pay walls, analytics and ...",
        "business_type":"Business",
        "revenue_model":"Services & Subscriptions",
        "years_operating":"15 years",
        "netProfit":"GBP €676 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $96,473",
        "multiple_label":"Multiple",
        "profit_multiple":"7.5x Profit",
        "revenue_multiple":"1.8x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $79,460"
    },
    {
        "url":"https://flippa.com/11816323",
        "image":"https://static2.flippa.com/webp_5eee0cc5-adc1-4b7d-b322-a5a51d62fad6.png",
        "title":"tattoobuild.com",
        "listing_type":"Verified Listing",
        "country":"Canada",
        "description":"September Revenue $2,078 // At 100k monthly sessions, growing at 29% MoM // SaaS & Ad Revenue // Traffic from Google & Pinterest",
        "business_type":"Design and Style",
        "revenue_model":"Ads",
        "years_operating":"<1 year",
        "netProfit":"USD $165 p/mo",
        "pricing_label":"Asking price",
        "price":"USD $49,500",
        "multiple_label":"Multiple",
        "profit_multiple":"33.4x Profit",
        "revenue_multiple":"11.9x Revenue",
        "final_pricing_label":"Asking price",
        "final_price":"USD $49,500"
    }
];